#Venn diagramms of shared pathways
library(devtools)    
install_github("guokai8/VennDetail")
library(VennDetail)
library(readxl)
library(tidyverse)
library(utils)
#Pt11
#KEGG
LMPP_KEGG11<-read_tsv("results/Pt9/GSEA_pt11_BL_REL_LMPP_KEGG.tsv")
MPP_KEGG11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_MPP_KEGG.tsv")
earlyGMP_KEGG11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_earlyGMP_KEGG.tsv")
Progenitors_KEGG11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_Progenitors_KEGG.tsv")
venn11_KEGG<-venndetail(list(LMPP = LMPP_KEGG11$pathway, MPP=MPP_KEGG11$pathway, earlyGMP=earlyGMP_KEGG11$pathway, Progenitors = Progenitors_KEGG11$pathway))
plot(venn11_KEGG)
detail(venn11_KEGG)
write_csv(result(venn11_KEGG), "results/Pt11/fgsea/Pt11_shared_KEGG.csv")
#GO
LMPP_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_LMPP_GO.tsv")
MPP_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_MPP_GO.tsv")
earlyGMP_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_earlyGMP_GO.tsv")
Progenitors_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_Progenitors_GO.tsv")
venn11_GO<-venndetail(list(LMPP = LMPP_GO11$pathway, MPP=MPP_GO11$pathway, earlyGMP=earlyGMP_GO11$pathway, Progenitors = Progenitors_GO11$pathway))
plot(venn11_GO)
detail(venn11_GO)
write_csv(result(venn11_GO), "results/Pt11/fgsea/Pt11_shared_GO.csv")
#Hallmark
LMPP_HALLMARK11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_LMPP_HALLMARK.tsv")
MPP_HALLMARK11<-read_csv("results/Pt11/fgsea/GSEA_pt11_MPP_HALLMARK.csv")
earlyGMP_HALLMARK11<-read_csv("results/Pt11/fgsea/GSEA_pt11_earlyGMP_HALLMARK.csv")
Progenitors_HALLMARK11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_Progenitors_HALLMARK.tsv")
venn11_HALLMARK<-venndetail(list(LMPP = LMPP_HALLMARK11$pathway, MPP=MPP_HALLMARK11$pathway, earlyGMP=earlyGMP_HALLMARK11$pathway, Progenitors = Progenitors_HALLMARK11$pathway))
plot(venn11_HALLMARK)
detail(venn11_HALLMARK)
write_csv(result(venn11_HALLMARK), "results/Pt11/fgsea/Pt11_shared_Hallmark.csv")

#Pt9
#KEGG
LMPP_KEGG9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_LMPP_KEGG.tsv")
MPP_KEGG9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_MPP_KEGG.tsv")
HSC_KEGG9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_HSC_KEGG.tsv")
venn9_KEGG<-venndetail(list(LMPP = LMPP_KEGG9$pathway, MPP=MPP_KEGG9$pathway, HSC=HSC_KEGG9$pathway))
plot(venn9_KEGG)
detail(venn9_KEGG)
write_csv(result(venn11_KEGG), "results/Pt9/Pt9_shared_KEGG.csv")
#GO
LMPP_GO9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_LMPP_GO.tsv")
MPP_GO9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_MPP_GO.tsv")
HSC_GO9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_HSC_GO.tsv")
venn9_GO<-venndetail(list(LMPP = LMPP_GO9$pathway, MPP=MPP_GO9$pathway, HSC=HSC_GO9$pathway))
plot(venn9_GO)
detail(venn9_GO)
write_csv(result(venn9_GO), "results/Pt9/Pt9_shared_GO.csv")
#Hallmark
LMPP_HALLMARK9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_LMPP_HALLMARK.tsv")
MPP_HALLMARK9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_MPP_HALLMARK.tsv")
HSC_HALLMARK9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_HSC_HALMARK.tsv")
venn9_HALLMARK<-venndetail(list(LMPP = LMPP_HALLMARK9$pathway, MPP=MPP_HALLMARK9$pathway, HSC=HSC_HALLMARK9$pathway))
plot(venn9_HALLMARK)
detail(venn9_HALLMARK)
write_csv(result(venn9_HALLMARK), "results/Pt9/Pt9_shared_HALLMARK.csv")

#What's the overlap between Pt11 and pt9
#KEGG
pt11KEGG<-read_csv("results/Pt11/fgsea/Pt11_shared_KEGG.csv")
pt9KEGG<-read_csv("results/Pt9/Pt9_shared_KEGG.csv")
Venn_sharedKEGG<-venndetail((list(pt9 = pt9KEGG$Detail, pt11=pt11KEGG$Detail)))
plot(Venn_sharedKEGG)
write_csv(result(Venn_sharedKEGG), "results/Pt9_and_11_shared_KEGG.csv")
#GO
pt11GO<-read_csv("results/Pt11/fgsea/Pt11_shared_GO.csv")
pt9GO<-read_csv("results/Pt9/Pt9_shared_GO.csv")
Venn_sharedGO<-venndetail((list(pt9 = pt9GO$Detail, pt11=pt11GO$Detail)))
plot(Venn_sharedGO)
write_csv(result(Venn_sharedGO), "results/Pt9_and_11_shared_GO.csv")
#HALLMARK
pt11HALLMARK<-read_csv("results/Pt11/fgsea/Pt11_shared_HALLMARK.csv")
pt9HALLMARK<-read_csv("results/Pt9/Pt9_shared_HALLMARK.csv")
Venn_sharedHALLMARK<-venndetail((list(pt9 = pt9HALLMARK$Detail, pt11=pt11HALLMARK$Detail)))
plot(Venn_sharedHALLMARK)
write_csv(result(Venn_sharedHALLMARK), "results/Pt9_and_11_shared_HALLMARK.csv")

#Pt4
#KEGG
MPP_KEGG4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MPP_KEGG.tsv")
HSC_KEGG4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_HSC_KEGG.tsv")
MEP_KEGG4<-read_csv("results/Pt4/fgsea/GSEA_pt4_MEP_KEGG.csv")
venn4_KEGG<-venndetail(list(MPP = MPP_KEGG4$pathway, MEP=MEP_KEGG4$pathway, HSC=HSC_KEGG4$pathway))
plot(venn4_KEGG)
detail(venn4_KEGG)
write_csv(result(venn4_KEGG), "results/Pt4/Pt4_shared_KEGG.csv")
#GO
LMPP_GO4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_LMPP_GO.tsv")
MPP_GO4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MPP_GO.tsv")
HSC_GO4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_HSC_GO.tsv")
MEP_GO4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MEP_GO.tsv")
venn4_GO<-venndetail(list(LMPP = LMPP_GO4$pathway, MPP=MPP_GO4$pathway, MEP=MEP_GO4$pathway,HSC=HSC_GO4$pathway))
plot(venn4_GO)
detail(venn4_GO)
write_csv(result(venn4_GO), "results/Pt4/Pt4_shared_GO.csv")
#Hallmark
MPP_HALLMARK4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MPP_HALLMARK.tsv")
MEP_HALLMARK4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MEP_HALLMARK.tsv")
HSC_HALLMARK4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_HSC_HALLMARK.tsv")
venn4_HALLMARK<-venndetail(list(MPP = MPP_HALLMARK4$pathway, MEP=MEP_HALLMARK4$pathway, HSC=HSC_HALLMARK4$pathway))
plot(venn4_HALLMARK)
detail(venn4_HALLMARK)
write_csv(result(venn4_HALLMARK), "results/Pt4/Pt4_shared_HALLMARK.csv")

#Pt14
#KEGG
MPP_KEGG14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_MPP_KEGG.tsv")
LMPP_KEGG14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_LMPP_KEGG.tsv")
venn14_KEGG<-venndetail(list(MPP = MPP_KEGG14$pathway, LMPP=LMPP_KEGG14$pathway))
plot(venn14_KEGG)
detail(venn14_KEGG)
write_csv(result(venn14_KEGG), "results/Pt14/Pt14_shared_KEGG.csv")
#GO
MPP_GO14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_MPP_GO.tsv")
LMPP_GO14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_LMPP_GO.tsv")
venn14_GO<-venndetail(list(MPP = MPP_GO14$pathway, LMPP=LMPP_GO14$pathway))
plot(venn14_GO)
detail(venn14_GO)
write_csv(result(venn14_GO), "results/Pt14/Pt14_shared_GO.csv")
#Hallmark
MPP_HALLMARK14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_MPP_HALLMARK.tsv")
LMPP_HALLMARK14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_LMPP_HALLMARK.tsv")
venn14_HALLMARK<-venndetail(list(MPP = MPP_HALLMARK14$pathway, LMPP=LMPP_HALLMARK14$pathway))
plot(venn14_HALLMARK)
detail(venn14_HALLMARK)
write_csv(result(venn14_HALLMARK), "results/Pt14/Pt14_shared_HALLMARK.csv")

#That included all the pathways, it may make more sense to include the significant ones only
#Pt11
#KEGG
LMPP_KEGG11<-read_tsv("results/Pt9/GSEA_pt11_BL_REL_LMPP_KEGG.tsv")
LMPP_KEGG11_sig = subset(LMPP_KEGG11, LMPP_KEGG11$padj<=0.05)
MPP_KEGG11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_MPP_KEGG.tsv")
MPP_KEGG11_sig = subset(MPP_KEGG11, MPP_KEGG11$padj<=0.05)
earlyGMP_KEGG11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_earlyGMP_KEGG.tsv")
earlyGMP_KEGG11_sig = subset(earlyGMP_KEGG11, earlyGMP_KEGG11$padj<=0.05)
Progenitors_KEGG11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_Progenitors_KEGG.tsv")
Progenitors_KEGG11_sig = subset(Progenitors_KEGG11, Progenitors_KEGG11$padj<=0.05)
venn11_KEGG<-venndetail(list(LMPP = LMPP_KEGG11_sig$pathway, MPP=MPP_KEGG11_sig$pathway, earlyGMP=earlyGMP_KEGG11_sig$pathway, Progenitors = Progenitors_KEGG11_sig$pathway))
plot(venn11_KEGG)
detail(venn11_KEGG)
write_csv(result(venn11_KEGG), "results/Pt11/fgsea/Pt11_shared_KEGG_sig.csv")
#GO
LMPP_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_LMPP_GO.tsv")
LMPP_GO11_sig = subset(LMPP_GO11, LMPP_GO11$padj<=0.05)
MPP_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_MPP_GO.tsv")
MPP_GO11_sig = subset(MPP_GO11, MPP_GO11$padj<=0.05)
earlyGMP_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_earlyGMP_GO.tsv")
earlyGMP_GO11_sig = subset(earlyGMP_GO11, earlyGMP_GO11$padj<=0.05)
Progenitors_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_Progenitors_GO.tsv")
Progenitors_GO11_sig = subset(Progenitors_GO11, Progenitors_GO11$padj<=0.05)
venn11_GO<-venndetail(list(LMPP = LMPP_GO11_sig$pathway, MPP=MPP_GO11_sig$pathway, earlyGMP=earlyGMP_GO11_sig$pathway, Progenitors = Progenitors_GO11_sig$pathway))
plot(venn11_GO)
detail(venn11_GO)
write_csv(result(venn11_GO), "results/Pt11/fgsea/Pt11_shared_GO_sig.csv")
#Hallmark
LMPP_HALLMARK11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_LMPP_HALLMARK.tsv")
LMPP_HALLMARK11_sig = subset(LMPP_HALLMARK11, LMPP_HALLMARK11$padj<=0.05)
MPP_HALLMARK11<-read_csv("results/Pt11/fgsea/GSEA_pt11_MPP_HALLMARK.csv")
MPP_HALLMARK11_sig = subset(MPP_HALLMARK11, MPP_HALLMARK11$padj<=0.05)
earlyGMP_HALLMARK11<-read_csv("results/Pt11/fgsea/GSEA_pt11_earlyGMP_HALLMARK.csv")
earlyGMP_HALLMARK11_sig = subset(earlyGMP_HALLMARK11, earlyGMP_HALLMARK11$padj<=0.05)
Progenitors_HALLMARK11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_Progenitors_HALLMARK.tsv")
Progenitors_HALLMARK11_sig = subset(Progenitors_HALLMARK11, Progenitors_HALLMARK11$padj<=0.05)
venn11_HALLMARK<-venndetail(list(LMPP = LMPP_HALLMARK11_sig$pathway, MPP=MPP_HALLMARK11_sig$pathway, earlyGMP=earlyGMP_HALLMARK11_sig$pathway, Progenitors = Progenitors_HALLMARK11_sig$pathway))
plot(venn11_HALLMARK)
detail(venn11_HALLMARK)
write_csv(result(venn11_HALLMARK), "results/Pt11/fgsea/Pt11_shared_Hallmark_sig.csv")

#Pt9
#KEGG
LMPP_KEGG9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_LMPP_KEGG.tsv")
LMPP_KEGG9_sig = subset(LMPP_KEGG9, LMPP_KEGG9$padj <= 0.05)
MPP_KEGG9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_MPP_KEGG.tsv")
MPP_KEGG9_sig = subset(MPP_KEGG9, MPP_KEGG9$padj<=0.05)
HSC_KEGG9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_HSC_KEGG.tsv")
HSC_KEGG9_sig = subset (HSC_KEGG9, HSC_KEGG9$padj<=0.05)
venn9_KEGG<-venndetail(list(LMPP = LMPP_KEGG9_sig$pathway, MPP=MPP_KEGG9_sig$pathway, HSC=HSC_KEGG9_sig$pathway))
plot(venn9_KEGG)
detail(venn9_KEGG)
write_csv(result(venn9_KEGG), "results/Pt9/Pt9_shared_KEGG_sig.csv")
#GO
LMPP_GO9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_LMPP_GO.tsv")
LMPP_GO9_sig = subset(LMPP_GO9, LMPP_GO9$padj <= 0.05)
MPP_GO9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_MPP_GO.tsv")
MPP_GO9_sig = subset(MPP_GO9, MPP_GO9$padj <= 0.05)
HSC_GO9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_HSC_GO.tsv")
HSC_GO9_sig = subset(HSC_GO9, HSC_GO9$padj <= 0.05)
venn9_GO<-venndetail(list(LMPP = LMPP_GO9_sig$pathway, MPP=MPP_GO9_sig$pathway, HSC=HSC_GO9_sig$pathway))
plot(venn9_GO)
detail(venn9_GO)
write_csv(result(venn9_GO), "results/Pt9/Pt9_shared_GO_sig.csv")
#Hallmark
LMPP_HALLMARK9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_LMPP_HALLMARK.tsv")
LMPP_HALLMARK9_sig = subset(LMPP_HALLMARK9, LMPP_HALLMARK9$padj <= 0.05)
MPP_HALLMARK9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_MPP_HALLMARK.tsv")
MPP_HALLMARK9_sig = subset(MPP_HALLMARK9, MPP_HALLMARK9$padj <= 0.05)
HSC_HALLMARK9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_HSC_HALMARK.tsv")
HSC_HALLMARK9_sig = subset(HSC_HALLMARK9, HSC_HALLMARK9$padj <= 0.05)
venn9_HALLMARK<-venndetail(list(LMPP = LMPP_HALLMARK9_sig$pathway, MPP=MPP_HALLMARK9_sig$pathway, HSC=HSC_HALLMARK9_sig$pathway))
plot(venn9_HALLMARK)
detail(venn9_HALLMARK)
write_csv(result(venn9_HALLMARK), "results/Pt9/Pt9_shared_HALLMARK_sig.csv")

#That results in a pretty small overlap, we could now test it with a cutoff of 0.1
#Pt11
#KEGG
LMPP_KEGG11<-read_tsv("results/Pt9/GSEA_pt11_BL_REL_LMPP_KEGG.tsv")
LMPP_KEGG11_sig = subset(LMPP_KEGG11, LMPP_KEGG11$padj<=0.1)
MPP_KEGG11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_MPP_KEGG.tsv")
MPP_KEGG11_sig = subset(MPP_KEGG11, MPP_KEGG11$padj<=0.1)
earlyGMP_KEGG11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_earlyGMP_KEGG.tsv")
earlyGMP_KEGG11_sig = subset(earlyGMP_KEGG11, earlyGMP_KEGG11$padj<=0.1)
Progenitors_KEGG11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_Progenitors_KEGG.tsv")
Progenitors_KEGG11_sig = subset(Progenitors_KEGG11, Progenitors_KEGG11$padj<=0.1)
venn11_KEGG<-venndetail(list(LMPP = LMPP_KEGG11_sig$pathway, MPP=MPP_KEGG11_sig$pathway, earlyGMP=earlyGMP_KEGG11_sig$pathway, Progenitors = Progenitors_KEGG11_sig$pathway))
plot(venn11_KEGG)
detail(venn11_KEGG)
write_csv(result(venn11_KEGG), "results/Pt11/fgsea/Pt11_shared_KEGG_<0.1.csv")
#GO
LMPP_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_LMPP_GO.tsv")
LMPP_GO11_sig = subset(LMPP_GO11, LMPP_GO11$padj<=0.1)
MPP_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_MPP_GO.tsv")
MPP_GO11_sig = subset(MPP_GO11, MPP_GO11$padj<=0.1)
earlyGMP_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_earlyGMP_GO.tsv")
earlyGMP_GO11_sig = subset(earlyGMP_GO11, earlyGMP_GO11$padj<=0.1)
Progenitors_GO11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_Progenitors_GO.tsv")
Progenitors_GO11_sig = subset(Progenitors_GO11, Progenitors_GO11$padj<=0.1)
venn11_GO<-venndetail(list(LMPP = LMPP_GO11_sig$pathway, MPP=MPP_GO11_sig$pathway, earlyGMP=earlyGMP_GO11_sig$pathway, Progenitors = Progenitors_GO11_sig$pathway))
plot(venn11_GO)
detail(venn11_GO)
write_csv(result(venn11_GO), "results/Pt11/fgsea/Pt11_shared_GO_<0.1.csv")
#Hallmark
LMPP_HALLMARK11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_LMPP_HALLMARK.tsv")
LMPP_HALLMARK11_sig = subset(LMPP_HALLMARK11, LMPP_HALLMARK11$padj<=0.1)
MPP_HALLMARK11<-read_csv("results/Pt11/fgsea/GSEA_pt11_MPP_HALLMARK.csv")
MPP_HALLMARK11_sig = subset(MPP_HALLMARK11, MPP_HALLMARK11$padj<=0.1)
earlyGMP_HALLMARK11<-read_csv("results/Pt11/fgsea/GSEA_pt11_earlyGMP_HALLMARK.csv")
earlyGMP_HALLMARK11_sig = subset(earlyGMP_HALLMARK11, earlyGMP_HALLMARK11$padj<=0.1)
Progenitors_HALLMARK11<-read_tsv("results/Pt11/fgsea/GSEA_pt11_BL_REL_Progenitors_HALLMARK.tsv")
Progenitors_HALLMARK11_sig = subset(Progenitors_HALLMARK11, Progenitors_HALLMARK11$padj<=0.1)
venn11_HALLMARK<-venndetail(list(LMPP = LMPP_HALLMARK11_sig$pathway, MPP=MPP_HALLMARK11_sig$pathway, earlyGMP=earlyGMP_HALLMARK11_sig$pathway, Progenitors = Progenitors_HALLMARK11_sig$pathway))
plot(venn11_HALLMARK)
detail(venn11_HALLMARK)
write_csv(result(venn11_HALLMARK), "results/Pt11/fgsea/Pt11_shared_Hallmark_<0.1.csv")

#Pt9
#KEGG
LMPP_KEGG9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_LMPP_KEGG.tsv")
LMPP_KEGG9_sig = subset(LMPP_KEGG9, LMPP_KEGG9$padj <= 0.1)
MPP_KEGG9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_MPP_KEGG.tsv")
MPP_KEGG9_sig = subset(MPP_KEGG9, MPP_KEGG9$padj<=0.1)
HSC_KEGG9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_HSC_KEGG.tsv")
HSC_KEGG9_sig = subset (HSC_KEGG9, HSC_KEGG9$padj<=0.1)
venn9_KEGG<-venndetail(list(LMPP = LMPP_KEGG9_sig$pathway, MPP=MPP_KEGG9_sig$pathway, HSC=HSC_KEGG9_sig$pathway))
plot(venn9_KEGG)
detail(venn9_KEGG)
write_csv(result(venn9_KEGG), "results/Pt9/Pt9_shared_KEGG_p<0.1.csv")
#GO
LMPP_GO9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_LMPP_GO.tsv")
LMPP_GO9_sig = subset(LMPP_GO9, LMPP_GO9$padj <= 0.1)
MPP_GO9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_MPP_GO.tsv")
MPP_GO9_sig = subset(MPP_GO9, MPP_GO9$padj <= 0.1)
HSC_GO9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_HSC_GO.tsv")
HSC_GO9_sig = subset(HSC_GO9, HSC_GO9$padj <= 0.1)
venn9_GO<-venndetail(list(LMPP = LMPP_GO9_sig$pathway, MPP=MPP_GO9_sig$pathway, HSC=HSC_GO9_sig$pathway))
plot(venn9_GO)
detail(venn9_GO)
write_csv(result(venn9_GO), "results/Pt9/Pt9_shared_GO_<0.1.csv")
#Hallmark
LMPP_HALLMARK9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_LMPP_HALLMARK.tsv")
LMPP_HALLMARK9_sig = subset(LMPP_HALLMARK9, LMPP_HALLMARK9$padj <= 0.1)
MPP_HALLMARK9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_MPP_HALLMARK.tsv")
MPP_HALLMARK9_sig = subset(MPP_HALLMARK9, MPP_HALLMARK9$padj <= 0.1)
HSC_HALLMARK9<-read_tsv("results/Pt9/GSEA_pt9_BL_REL_HSC_HALMARK.tsv")
HSC_HALLMARK9_sig = subset(HSC_HALLMARK9, HSC_HALLMARK9$padj <= 0.1)
venn9_HALLMARK<-venndetail(list(LMPP = LMPP_HALLMARK9_sig$pathway, MPP=MPP_HALLMARK9_sig$pathway, HSC=HSC_HALLMARK9_sig$pathway))
plot(venn9_HALLMARK)
detail(venn9_HALLMARK)
write_csv(result(venn9_HALLMARK), "results/Pt9/Pt9_shared_HALLMARK_<0.1.csv")

#Pt4
#KEGG
MPP_KEGG4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MPP_KEGG.tsv")
MPP_KEGG4_sig = subset(MPP_KEGG4, MPP_KEGG4$padj<=0.1)
HSC_KEGG4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_HSC_KEGG.tsv")
HSC_KEGG4_sig = subset(HSC_KEGG4, HSC_KEGG4$padj<=0.1)
MEP_KEGG4<-read_csv("results/Pt4/fgsea/GSEA_pt4_MEP_KEGG.csv")
MEP_KEGG4_sig = subset(MEP_KEGG4, MEP_KEGG4$padj<=0.1)
venn4_KEGG_sig<-venndetail(list(MPP = MPP_KEGG4_sig$pathway, MEP=MEP_KEGG4_sig$pathway, HSC=HSC_KEGG4_sig$pathway))
plot(venn4_KEGG_sig)
detail(venn4_KEGG_sig)
write_csv(result(venn4_KEGG_sig), "results/Pt4/Pt4_shared_KEGG_p<0.1.csv")
#GO
LMPP_GO4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_LMPP_GO.tsv")
LMPP_GO4_sig = subset(LMPP_GO4, LMPP_GO4$padj<=0.1)
MPP_GO4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MPP_GO.tsv")
MPP_GO4_sig = subset(MPP_GO4, MPP_GO4$padj<=0.1)
HSC_GO4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_HSC_GO.tsv")
HSC_GO4_sig = subset(HSC_GO4, HSC_GO4$padj<=0.1)
MEP_GO4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MEP_GO.tsv")
MEP_GO4_sig = subset(MEP_GO4, MEP_GO4$padj<=0.1)
venn4_GO_sig<-venndetail(list(LMPP = LMPP_GO4_sig$pathway, MPP=MPP_GO4_sig$pathway, MEP=MEP_GO4_sig$pathway,HSC=HSC_GO4_sig$pathway))
plot(venn4_GO_sig)
detail(venn4_GO)
write_csv(result(venn4_GO_sig), "results/Pt4/Pt4_shared_GO_sig.csv")
#Hallmark
MPP_HALLMARK4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MPP_HALLMARK.tsv")
MPP_HALLMARK4_sig= subset(MPP_HALLMARK4, MPP_HALLMARK4$padj<=0.1)
MEP_HALLMARK4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_MEP_HALLMARK.tsv")
MEP_HALLMARK4_sig= subset(MEP_HALLMARK4, MEP_HALLMARK4$padj<=0.1)
HSC_HALLMARK4<-read_tsv("results/Pt4/fgsea/GSEA_pt4_BL_REL_HSC_HALLMARK.tsv")
HSC_HALLMARK4_sig= subset(HSC_HALLMARK4, HSC_HALLMARK4$padj<=0.1)
venn4_HALLMARK_sig<-venndetail(list(MPP = MPP_HALLMARK4_sig$pathway, MEP=MEP_HALLMARK4_sig$pathway, HSC=HSC_HALLMARK4_sig$pathway))
plot(venn4_HALLMARK)
detail(venn4_HALLMARK)
write_csv(result(venn4_HALLMARK), "results/Pt4/Pt4_shared_HALLMARK_sig.csv")

#Pt14
#KEGG
MPP_KEGG14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_MPP_KEGG.tsv")
MPP_KEGG14_sig = subset(MPP_KEGG14, MPP_KEGG14$padj<=0.1)
LMPP_KEGG14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_LMPP_KEGG.tsv")
LMPP_KEGG14_sig = subset(LMPP_KEGG14, LMPP_KEGG14$padj<=0.1)
venn14_KEGG_sig<-venndetail(list(MPP = MPP_KEGG14_sig$pathway, LMPP=LMPP_KEGG14_sig$pathway))
plot(venn14_KEGG_sig)
detail(venn14_KEGG_sig)
write_csv(result(venn14_KEGG_sig), "results/Pt14/Pt14_shared_KEGG_sig.csv")
#GO
MPP_GO14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_MPP_GO.tsv")
MPP_GO14_sig = subset(MPP_GO14, MPP_GO14$padj<=0.1)
LMPP_GO14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_LMPP_GO.tsv")
LMPP_GO14_sig = subset(LMPP_GO14, LMPP_GO14$padj<=0.1)
venn14_GO_sig<-venndetail(list(MPP = MPP_GO14_sig$pathway, LMPP=LMPP_GO14_sig$pathway))
plot(venn14_GO_sig)
detail(venn14_GO_sig)
write_csv(result(venn14_GO), "results/Pt14/Pt14_shared_GO_sig.csv")
#Hallmark
MPP_HALLMARK14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_MPP_HALLMARK.tsv")
MPP_HALLMARK14_sig = subset(MPP_HALLMARK14, MPP_HALLMARK14$padj<=0.1)
LMPP_HALLMARK14<-read_tsv("results/Pt14/fgsea/GSEA_pt14_BL_REL_LMPP_HALLMARK.tsv")
LMPP_HALLMARK14_sig = subset(LMPP_HALLMARK14, LMPP_HALLMARK14$padj<=0.1)
venn14_HALLMARK_sig<-venndetail(list(MPP = MPP_HALLMARK14_sig$pathway, LMPP=LMPP_HALLMARK14_sig$pathway))
plot(venn14_HALLMARK_sig)
detail(venn14_HALLMARK_sig)
write_csv(result(venn14_HALLMARK_sig), "results/Pt14/Pt14_shared_HALLMARK_sig.csv")

#What's the overlap between Pt11 and pt9
#KEGG
pt11KEGG<-read_csv("results/Pt11/fgsea/Pt11_shared_KEGG.csv")
pt9KEGG<-read_csv("results/Pt9/Pt9_shared_KEGG.csv")
Venn_sharedKEGG<-venndetail((list(pt9 = pt9KEGG$Detail, pt11=pt11KEGG$Detail)))
plot(Venn_sharedKEGG)
write_csv(result(Venn_sharedKEGG), "results/Pt9_and_11_shared_KEGG.csv")
#GO
pt11GO<-read_csv("results/Pt11/fgsea/Pt11_shared_GO.csv")
pt9GO<-read_csv("results/Pt9/Pt9_shared_GO.csv")
Venn_sharedGO<-venndetail((list(pt9 = pt9GO$Detail, pt11=pt11GO$Detail)))
plot(Venn_sharedGO)
write_csv(result(Venn_sharedGO), "results/Pt9_and_11_shared_GO.csv")
#HALLMARK
pt11HALLMARK<-read_csv("results/Pt11/fgsea/Pt11_shared_HALLMARK.csv")
pt9HALLMARK<-read_csv("results/Pt9/Pt9_shared_HALLMARK.csv")
Venn_sharedHALLMARK<-venndetail((list(pt9 = pt9HALLMARK$Detail, pt11=pt11HALLMARK$Detail)))
plot(Venn_sharedHALLMARK)
write_csv(result(Venn_sharedHALLMARK), "results/Pt9_and_11_shared_HALLMARK.csv")
