---
title: "Pt11_LMPP_DGE_visualisation"
output: html_document
date: "2024-06-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the previous code we got lists of differentially expressed genes. The following code will visualise the results.
Read in the data.
```{r}
deseq<- read.csv("results/Pt11/results/Deseq2/DEA_pt11_LMPP.csv")
dream<-read.csv("results/Pt11/results/Dream/Pt11_DREAM_LMPP.csv")
deseq_sig = subset(deseq, deseq$padj<0.05)
dream_sig = subset(dream, dream$adjusted.pval<0.05)
```
Correlation between Dream and Deseq results.
```{r}
library(smplot2)
library(tidyverse)
```

```{r}
joined<-dream %>%
  left_join(deseq, by = c("Gene" = "gene"))
correlation<-joined %>% 
  ggplot(aes(x = log2FoldChange, y = log2FC))+
  geom_point()+
  sm_statCorr(color = '#0f993d', corr_method = 'spearman',
              linetype = 'dashed')
ggsave("Correlation_pt11_LMPP_DGE.pdf", plot = correlation, path = "results/Pt11/results/Figures", width =10, height = 10, unit = "cm")
correlation
```
```{r}
correlation_p<-joined %>% 
  ggplot(aes(x = p.value, y = pvalue))+
  geom_point()+
  sm_statCorr(color = '#0f993d', corr_method = 'spearman',
              linetype = 'dashed')
correlation_p
```
```{r}
joined_sig<-dream_sig %>%
  left_join(deseq_sig, by = c("Gene" = "gene"))
correlation_p<-joined_sig %>% 
  ggplot(aes(x = , y = padj))+
  geom_point()+
  sm_statCorr(color = '#0f993d', corr_method = 'spearman',
              linetype = 'dashed')
correlation_p
```


Volcano Plots
```{r}
library(EnhancedVolcano)
```
```{r}
deseq<-deseq %>% mutate(threshold=padj <0.05 & abs(log2FoldChange)>0.58)
deseq_sig<-deseq%>%filter(padj<0.05&log2FoldChange>2|padj<0.05&log2FoldChange<"-2")
deseq_sig<-deseq_sig[order(deseq_sig$log2FoldChange, decreasing = TRUE),]
head(deseq_sig)
tail(deseq_sig)
top10genesup<-head(deseq_sig$gene, 15)
top10genesdown<-tail(deseq_sig$gene, 15)
regulons_up<-c(regulons$`TCF4(+)`, regulons$`POU4F1(+)`, regulons$`TFAP4(+)`, regulons$`STAT6(+)`)
regulons_down<-c(regulons$`EGR1(+)`, regulons$IRF4, regulons$`ATF3(+)`, regulons$`HIVEP2(+)`)
top10genesdown
top10genesup
library(clusterProfiler)
list<-read.gmt("data/GSEA_references/Reference gene sets/msigdb_v2023.2.Hs_GMTs/VALK_AML_WITH_FLT3_ITD.v2023.2.Hs.gmt")
DeseqVolcano<-
  EnhancedVolcano(deseq_sig,
                lab = deseq_sig$gene,
                title = "Pt11 LMPP differentially expressed genes",
                selectLab = c("SORT1", "DPYSL2", "ATP10A", "PDE4D", "SEM3A3", "HBB", "CCSER1", "DACH1", "AREG", "SEMA3A", "RXFP1", "VNN1"),
                x = 'log2FoldChange',
                y = 'pvalue',
                col=c('black', 'lightgreen', 'lightblue', 'red3'),
                pointSize = 4.0,
    labSize = 6.0,
    labCol = 'black',
    labFace = 'bold',
    boxedLabels = TRUE,
    colAlpha = 4/5,
    legendPosition = 'right',
    legendLabSize = 14,
    legendIconSize = 4.0,
    drawConnectors = TRUE,
    widthConnectors = 1.0,
    colConnectors = 'black',
    ylim = c(0,150))
ggsave("Volcano Plot_pt11_LMPP_Deseq2_regulons.pdf", plot = DeseqVolcano, path = "results/Pt11/results/Figures", width =20, height = 30, unit = "cm")
```
```{r}
DeseqVolcano
```

Volcano PLot where the leading edge genes of the Top pathways are annotated.
```{r}

inflammation<-c("AREG", "PER1", "DUSP1", "DENND5A", "MCL1", "JUN", "FOS", "NFKBIA", "KLF2", "IRF2", "FOSB")
OXPHOS<-c("COX6A1", "ATP5F1B", "ATP2B1", "ATP5MF", "NDUFAB1")
MYC<-c("HSPE1", "PPIA", "C1QBP",  "RAN",  "RPL6")

DeseqVolcano<-
  EnhancedVolcano(deseq_sig,
                lab = deseq_sig$gene,
                title = "Pt11 LMPP differentially expressed genes",
                selectLab = c(inflammation, OXPHOS, MYC),
                x = 'log2FoldChange',
                y = 'pvalue',
                col=c('black', 'lightgreen', 'lightblue', 'red3'),
                pointSize = 4.0,
    labSize = 6.0,
    labCol = 'black',
    labFace = 'bold',
    boxedLabels = TRUE,
    colAlpha = 4/5,
    legendPosition = 'right',
    legendLabSize = 14,
    legendIconSize = 4.0,
    drawConnectors = TRUE,
    widthConnectors = 1.0,
    colConnectors = 'black',
    ylim = c(0,150))
DeseqVolcano
```
```{r}
regulons$EGR1
```
```{r}
regulons$`IRF4(+)`
regulons$`ATF3(+)`
regulons$`HIVEP2(+)`
```
```{r}
top10genesdown
```
```{r}

```

Volcano Plot for DREAM
```{r}
dream<-dream %>% mutate(threshold=adjusted.pval <0.05 & abs(log2FC)>0.58)
dream_sig<-deseq%>%filter(padj<0.05&log2FoldChange>2|padj<0.05&log2FoldChange<"-2")
dream_sig<-dream_sig[order(dream_sig$log2FoldChange, decreasing = TRUE),]
head(dream_sig)
tail(dream_sig)
top10genesup<-head(dream_sig$gene, 10)
top10genesdown<-tail(deseq_sig$gene, 10)
top10genesdown
top10genesup
dream_Volcano<-EnhancedVolcano(dream,
                lab = dream$Gene,
                selectLab = c(top10genesup, top10genesdown),
                x = 'log2FC',
                y = 'adjusted.pval',
                title = "Pt11 LMPP differentially expressed genes",
                col=c('black', 'black', 'black', 'red3'),
                drawConnectors = TRUE,
                widthConnectors = 0.75, 
                xlim=c(-11, 10))
ggsave("Volcano Plot_pt11_LMPP_Dream.pdf", plot = dream_Volcano, path = "results/Pt11/results/Figures", width =20, height = 30, unit = "cm")
dream_Volcano
```
Ven Diagramm of the overlap of dream and deseq in LMPP
```{r}
library(devtools)    
install_github("guokai8/VennDetail")
library(VennDetail)
library(readxl)
library(tidyverse)
library(utils)
```
```{r}
venn11_dream_deseq<-venndetail(list(dream = dream_sig$Gene, deseq_sig$gene))
plot(venn11_dream_deseq)
```

